In [2]:
import pandas as pd
import numpy as np

In [4]:
trans = pd.read_csv('transactions.csv')
trans

             date  store_nbr  transactions
0      2013-01-01         25           770
1      2013-01-02          1          2111
2      2013-01-02          2          2358
3      2013-01-02          3          3487
4      2013-01-02          4          1922
5      2013-01-02          5          1903
6      2013-01-02          6          2143
7      2013-01-02          7          1874
8      2013-01-02          8          3250
9      2013-01-02          9          2940
10     2013-01-02         10          1293
11     2013-01-02         11          3547
12     2013-01-02         12          1362
13     2013-01-02         13          1102
14     2013-01-02         14          2002
15     2013-01-02         15          1622
16     2013-01-02         16          1167
17     2013-01-02         17          1580
18     2013-01-02         18          1635
19     2013-01-02         19          1369
20     2013-01-02         23          1381
21     2013-01-02         24          2605
22     2013-01-02         25          1038
23     2013-01-02         26          1008
24     2013-01-02         27          1386
25     2013-01-02         28           950
26     2013-01-02         30           708
27     2013-01-02         31          1401
28     2013-01-02         32           776
29     2013-01-02         33          1163
...           ...        ...           ...
83458  2017-08-15         25           849
83459  2017-08-15         26           534
83460  2017-08-15         27          1543
83461  2017-08-15         28          1343
83462  2017-08-15         29          1302
83463  2017-08-15         30           825
83464  2017-08-15         31          1360
83465  2017-08-15         32           615
83466  2017-08-15         33           919
83467  2017-08-15         34          2007
83468  2017-08-15         35           612
83469  2017-08-15         36          1192
83470  2017-08-15         37          1373
83471  2017-08-15         38          1445
83472  2017-08-15         39          1425
83473  2017-08-15         40          1392
83474  2017-08-15         41          1003
83475  2017-08-15         42           995
83476  2017-08-15         43          1482
83477  2017-08-15         44          3815
83478  2017-08-15         45          3685
83479  2017-08-15         46          3197
83480  2017-08-15         47          3581
83481  2017-08-15         48          2722
83482  2017-08-15         49          2814
83483  2017-08-15         50          2804
83484  2017-08-15         51          1573
83485  2017-08-15         52          2255
83486  2017-08-15         53           932
83487  2017-08-15         54           802

[83488 rows x 3 columns]

In [8]:
trans[1,2]

KeyError: (1, 2)